### ISSUE TITLE
problem with the json loader Mac

### ISSUE THREAD

**Issue by ldegroot** [gkudos/qgis-cartodb#11]
Hi,

SQL query works but I get the following error on a Mac. 

Great plugin though. Thanks for building.

Len

Traceback (most recent call last):
  File "/Users/user/.qgis2/python/plugins/QgisCartoDB/CartoDBPlugin.py", line 108, in run
    layer = CartoDBPluginLayer(self.iface, table.text(), dlg.currentUser, dlg.currentApiKey)
  File "/Users/user/.qgis2/python/plugins/QgisCartoDB/CartoDBPluginLayer.py", line 130, in __init__
    self._uneditableFields()
  File "/Users/user/.qgis2/python/plugins/QgisCartoDB/CartoDBPluginLayer.py", line 160, in _uneditableFields
    QgsMessageLog.logMessage(errorMsg + ' - ' + str(e), 'CartoDB Plugin', QgsMessageLog.CRITICAL)
NameError: global name 'errorMsg' is not defined

Python version:
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

QGIS version:
2.6.1-Brighton Brighton

**Comment by ldegroot** [comment]
And by JSON, I mean the non-SQL load. :)
