### ISSUE TITLE
JSON Value error

### ISSUE THREAD

**Issue by elesdoar** [gkudos/qgis-cartodb#24]
Error on CartoDB response

```python
Traceback (most recent call last):
  File "/home/juanmendez/.qgis2/python/plugins/QgisCartoDB/cartodb/cartodbapi.py", line 202, in returnFetchContent
    self.fetchContent.emit(json.loads(response))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by elesdoar** [comment]
Fix in 9220b4ffbdcbf4886664a0ce9069da80e03102f2
