### ISSUE TITLE
Upload issues

### ISSUE THREAD

**Issue by auerje** [gkudos/qgis-cartodb#43]
Traceback (most recent call last):
			  File "/Users/jensauer/.qgis2/python/plugins/QgisCartoDB/CartoDBPlugin.py", line 239, in upload
			    dlg = CartoDBPluginUpload(self.iface, self.toolbar)
			  File "/Users/jensauer/.qgis2/python/plugins/QgisCartoDB/dialogs/Upload.py", line 69, in __init__
			    qDebug('Layer id {}'.format(id_ly))
			UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 12: ordinal not in range(128)

**Comment by auerje** [comment]
on Qgis 2.14.1 Macosx, plugin version 0.23

**Comment by elesdoar** [comment]
Closing, duplicate #40
